# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_world.proto

require "google/protobuf"


descriptor_data = "\n\x11hello_world.proto\x12\x0bhello_world\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x07Greeter\x12>\n\x08SayHello\x12\x19.hello_world.HelloRequest\x1a\x17.hello_world.HelloReplyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module HelloWorld
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello_world.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello_world.HelloReply").msgclass
end
