# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: todo.proto for package 'todo'

require "grpc"
require "todo_pb"

module Todo
  module TodoService
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "todo.TodoService"

      rpc :ListTodos, ::Todo::Empty, ::Todo::TodoList
      rpc :GetTodo, ::Todo::TodoRequest, ::Todo::Todo
      rpc :CreateTodo, ::Todo::Todo, ::Todo::Todo
      rpc :UpdateTodo, ::Todo::Todo, ::Todo::Todo
      rpc :DeleteTodo, ::Todo::TodoRequest, ::Todo::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
