# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

require "google/protobuf"


descriptor_data = "\n\ntodo.proto\x12\x04todo\"\x07\n\x05\x45mpty\"I\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\"%\n\x08TodoList\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todo\"\x19\n\x0bTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xdb\x01\n\x0bTodoService\x12(\n\tListTodos\x12\x0b.todo.Empty\x1a\x0e.todo.TodoList\x12(\n\x07GetTodo\x12\x11.todo.TodoRequest\x1a\n.todo.Todo\x12$\n\nCreateTodo\x12\n.todo.Todo\x1a\n.todo.Todo\x12$\n\nUpdateTodo\x12\n.todo.Todo\x1a\n.todo.Todo\x12,\n\nDeleteTodo\x12\x11.todo.TodoRequest\x1a\x0b.todo.Emptyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Todo
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("todo.Empty").msgclass
  Todo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("todo.Todo").msgclass
  TodoList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("todo.TodoList").msgclass
  TodoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("todo.TodoRequest").msgclass
end
